### ISSUE TITLE
Adding powershell script file to MELPA

### ISSUE THREAD

**Issue by ahbc-sdg** [LionyxML/ros#9]
HI @LionyxML!

I reinstalled org-ros from melpa and I see that the powershell script for windows use doesn't appear in my package distribution
I reviewed the melpa recipe and I wonder if it needs to modified like 

```elisp
(org-ros
  :repo "LionyxML/ros"
  :fetcher github
  :files "*.ps1")
```

https://github.com/melpa/melpa/blob/master/recipes/org-ros

**Comment by LionyxML** [comment]
Thanks for noticing @ahbc-sdg!

I just created a PR for MELPA.
https://github.com/melpa/melpa/pull/9220

**Comment by LionyxML** [comment]
@ahbc-sdg , if you could please check it, my PR was merged into MELPA. It should be a complete bundle for Windows now.

**Comment by ahbc-sdg** [comment]
confirmed it works! thank you for the quick fix!
